title: Julius' Portfolio
description: > 
  <h3>Contact Me</h3>
  <a href="mailto: julius.sintara@gmail.com">julius.sintara@gmail.com</a> 
  <br>
  <a href="https://www.linkedin.com/in/juliussintara/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/juliussin/">GitHub Profile</a> 

theme: jekyll-theme-minimal
