title: Julius' Portfolio
description: > 
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/juliussintara/">LinkedIn Profile</a> 

theme: jekyll-theme-minimal
