title: Julius' Portfolio
logo: "/images/my_photo.png?raw=true"
description: > 
  <br>
  <b style="font-size:20px">Contact Me</b>
  <br>
  &nbsp;&nbsp;<a href="mailto: julius.sintara@gmail.com target="_blank"" title="julius.sintara@gmail.com">Email Me</a> 
  <br>
  &nbsp;&nbsp;<a href="https://www.linkedin.com/in/juliussintara/" target="_blank" title="https://www.linkedin.com/in/juliussintara/">LinkedIn Profile</a>
  <br>
  &nbsp;&nbsp;<a href="https://www.github.com/juliussin/" target="_blank" title="https://www.github.com/juliussin/">GitHub Profile</a> 
  <br><br>
  <h2>Table of Contents</h2>
  <a href="/">Welcome</a>
  <br><br>
  <a href="/portfolio">My Portfolio</a>
  <br><br>
  

markdown: kramdown
theme: jekyll-theme-minimal
google_analytics: UA-162757495-1
