title: Julius' Portfolio
logo: "/images/my_photo.png?raw=true"
description: > 
  <br>
  <b style="font-size:20px">Contact Me</b>
  <br>
  &nbsp;&nbsp;<a href="mailto: julius.sintara@gmail.com">Email Me</a> 
  <br>
  &nbsp;&nbsp;<a href="https://www.linkedin.com/in/juliussintara/">LinkedIn Profile</a>
  <br>
  &nbsp;&nbsp;<a href="https://www.github.com/juliussin/">GitHub Profile</a> 
  <br><br><br>
  <h2>Contents</h2>
  <a href="/">Welcome</a>
  <br>
  <a href="/iot">Internet of Things</a>
  <br>

markdown: kramdown
theme: jekyll-theme-minimal
