title: Julius' Portfolio
logo: "/images/my_photo.png?raw=true"
description: > 
  <br>
  <b style="font-size:20px">Contact Me</b>
  <br>
  &nbsp;&nbsp;<a href="mailto: julius.sintara@gmail.com">Email Me</a> 
  <br>
  &nbsp;&nbsp;<a href="https://www.linkedin.com/in/juliussintara/">LinkedIn Profile</a>
  <br>
  &nbsp;&nbsp;<a href="https://www.github.com/juliussin/">GitHub Profile</a> 
  <br><br>
  <h2>Table of Contents</h2>
  <a href="/">Summary</a>
  <br>
  <a href="#skills">Skills</a>
  <br>
  <a href="#water-heating-automation-system-for-swimming-pool">Water Heating Automation System for Swimming Pool</a>
  <br>
  <a href="#hexapod-robot-with-control-over-internet">Hexapod Robot with Control over Internet</a>
  <br>
  <a href="#diy-smart-ir-remote-connected-to-home-automation">DIY Smart IR Remote Connected to Home Automation</a>
  <br>
  

markdown: kramdown
theme: jekyll-theme-minimal
